### ISSUE TITLE
/help is currently broken

### ISSUE THREAD

**Issue by thesharp** [pietroalbini/botogram#37]
On current master when I try to invoke `/help` from my bot, I get this traceback:

```
Traceback (most recent call last):
  File "/home/serana/env/lib/python3.5/site-packages/botogram/runner/processes.py", line 54, in run
    self.loop()
  File "/home/serana/env/lib/python3.5/site-packages/botogram/runner/processes.py", line 158, in loop
    job.process(self.bots)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/runner/jobs.py", line 87, in process
    return self.func(bot, self.metadata)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/runner/jobs.py", line 96, in process_update
    bot.process(update)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/frozenbot.py", line 181, in process
    result = hook.call(self, update)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/hooks.py", line 45, in call
    return self._call(bot, update)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/hooks.py", line 182, in _call
    message=message, args=args)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/frozenbot.py", line 241, in _call
    return func(**kwargs)
  File "/home/serana/env/lib/python3.5/site-packages/botogram/defaults.py", line 45, in help_command
    commands = bot._get_commands()
  File "/home/serana/env/lib/python3.5/site-packages/botogram/frozenbot.py", line 216, in _get_commands
    return self._commands
AttributeError: 'FrozenBot' object has no attribute '_commands'

```

Bisect: 99f24a0dc062ba6c127462e13a9ffd6f1e7fd73a is the first bad commit
